[manager]
marker_copied   = { fg = "#2e9969", bg = "#2e9969" }
marker_cut      = { fg = "#cc5d4b", bg = "#cc5d4b" }
marker_marked   = { fg = "#ab78ab", bg = "#ab78ab" }
marker_selected = { fg = "#b38d59", bg = "#b38d59" }

cwd             = { fg = "#b38d59" }
hovered         = { reversed = true }
preview_hovered = { reversed = true }

find_keyword    = { fg = "#cc5d4b", bg = "#101010" }
find_position   = {}

tab_active      = { reversed = true }
tab_inactive    = {}
tab_width       = 1

count_copied    = { fg = "#0c0c0c", bg = "#2e9969" }
count_cut       = { fg = "#0c0c0c", bg = "#cc5d4b" }
count_selected  = { fg = "#0c0c0c", bg = "#b38d59" }

border_symbol   = "│"
border_style    = { fg = "#3d3d3d" } # bright_black

[mode]
normal_main = { fg = "#0c0c0c", bg = "#6179c2" }
normal_alt  = { fg = "#6179c2", bg = "#101010" }
select_main = { fg = "#0c0c0c", bg = "#ab78ab" }
select_alt  = { fg = "#ab78ab", bg = "#101010" }
unset_main  = { fg = "#0c0c0c", bg = "#b38d59" }
unset_alt   = { fg = "#b38d59", bg = "#101010" }

[status]
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }
overall   = { fg = "#f2e6cf", bg = "#0c0c0c" }

progress_label  = { fg = "#6179c2", bg = "#101010", bold = true }
progress_normal = { fg = "#0c0c0c", bg = "#3d3d3d" }
progress_error  = { fg = "#0c0c0c", bg = "#cc5d4b" }

perm_type  = { fg = "#6179c2" }
perm_read  = { fg = "#b38d59" }
perm_write = { fg = "#cc5d4b" }
perm_exec  = { fg = "#2e9969" }
perm_sep   = { fg = "#858585" }

[pick]
border   = { fg = "#3d3d3d" }
active   = { fg = "#ab78ab", bold = true }
inactive = {}

[input]
border   = { fg = "#3d3d3d" }
title    = {}
value    = {}
selected = { reversed = true }

[completion]
border   = { fg = "#3d3d3d" }
active   = { reversed = true }
inactive = {}

[tasks]
border  = { fg = "#3d3d3d" }
title   = {}
hovered = { fg = "#ab78ab" }

[which]
cols            = 2
separator       = " - "
separator_style = { fg = "#858585" }
mask            = { bg = "#0c0c0c" }
rest            = { fg = "#858585" }
cand            = { fg = "#6179c2" }
desc            = { fg = "#3d3d3d" }

[help]
on      = { fg = "#2e9969" }
run     = { fg = "#ab78ab" }
desc    = {}
hovered = { reversed = true, bold = true }
footer  = { fg = "#0c0c0c", bg = "#f2e6cf" }

[notify]
title_info  = { fg = "#6179c2" }
title_warn  = { fg = "#b38d59" }
title_error = { fg = "#cc5d4b" }

[icon]
dirs = [
    { name = ".config",      text = "", fg = "#ab78ab" },
    { name = ".git",         text = "", fg = "#6179c2" },
    { name = ".github",      text = "", fg = "#33919c" },
    { name = "Desktop",      text = "", fg = "#6179c2" },
    { name = "Development",  text = "", fg = "#b38d59" },
    { name = "Documents",    text = "", fg = "#6179c2" },
    { name = "Downloads",    text = "", fg = "#2e9969" },
    { name = "Movies",       text = "", fg = "#ab78ab" },
    { name = "Music",        text = "", fg = "#ab78ab" },
    { name = "Pictures",     text = "", fg = "#b38d59" },
    { name = "Videos",       text = "", fg = "#ab78ab" },
]

conds = [
    { if = "orphan", text = "", fg = "#cc5d4b" },
    { if = "link",   text = "", fg = "#858585" },
    { if = "sticky", text = "", fg = "#b38d59" },

    { if = "dir & hovered", text = "", fg = "#6179c2" },
    { if = "dir",           text = "", fg = "#6179c2" },

    { if = "exec",          text = "", fg = "#2e9969" },

    { if = "!dir",          text = "", fg = "#f2e6cf" },
]

[filetype]
rules = [
    # images
    { mime = "image/*", fg = "#b38d59" },

    # media
    { mime = "{audio,video}/*", fg = "#ab78ab" },

    # archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#d96857" },

    # documents
    { mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#33919c" },

    # broken links
    { name = "*", is = "orphan", fg = "#cc5d4b" },

    # executables
    { name = "*", is = "exec", fg = "#2e9969" },

    # directories / fallback
    { name = "*/", fg = "#6179c2" },
    { name = "*", fg = "#f2e6cf" },
]
